### PR TITLE
BATMAN Theme added and also resolved conflicts

### PR DESCRIPTION
**Pull request by prxthzmxdev**
Hey @JLambertazzo I resolved those conflicts as you mentioned and now the PR is ready to merge .... btw thanks for your guidance 💯

### CODE REVIEW

**Comment by DADDY-DOUBLESHOT** [comment]
Please don't forget to add hactoberfest label @JLambertazzo .

**Comment by JLambertazzo** [comment]
Unfortunately the changes are still here. If you check your files changed it's about 600 lines added, but it should be more like 3 or so for adding a theme. Can you look into this?

**Comment by DADDY-DOUBLESHOT** [comment]
Yeah I saw those changes but those were just alignment changes made by vs code as some lines were not aligned properly hence while saving these lines they were properly aligned you may have a look at the files changed only spaces and tabs are added

**Comment by JLambertazzo** [comment]
Unfortunately I still can't merge the alignment changes since if anyone else merges using a different style formatter we will have the same issue all over 😟

You can either change your formatter settings temporarily by pressing ctrl+shift+p and typing Formatter in vscode or make the updates using any text editor that doesn't have autoFormatOnSave

**Comment by DADDY-DOUBLESHOT** [comment]
ok @JLambertazzo  I will try to make those changes ....

**Pull request closed without merging**
